### ISSUE TITLE
Editable elements containing slashes cause syntax error with JQuery 1.8.x

### ISSUE THREAD

**Issue by weevilgenius** [caphun/jquery.inlineedit#19]
Editable elements containing the character "/" (in a url prefix, for example) trigger a syntax error with JQuery 1.8.x

To reproduce, edit the default.html file in the demos directory to use JQuery 1.8

``` html
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
```

And then modify one of the editable cell contents to include a /

``` html
  <tr><td><span class="editable">John/Doe</span></td></tr>
```

The browser (Safari in this case) shows a syntax error

```
Error: Syntax error, unrecognized expression: John/Doe
```

**Comment by weevilgenius** [comment]
After a bit more digging, the problem seems to be caused by line 182:

``` javascript
var value = $(newValue).text() === this.options.placeholder ? '' : newValue;
```

It looks like the value of the editable tag is passed in as a jQuery selector via `$(newValue)`.  If that value contains characters such as /, (), or [] which are meaningful as CSS selectors, the call will usually fail with an error.

Is there any reason this can't be changed to something simpler, such as this?

``` javascript
var value = newValue === this.placeholderHtml() ? '' : newValue;
```

**Comment by caphun** [comment]
@weevilgenius sorry for delayed response. can't see why not? send me a PR and I'll merge in the fix. Thanks!

**Comment by caphun** [comment]
merged. Thanks!
