### ISSUE TITLE
Can't manage to make encodeHtml work properly

### ISSUE THREAD

**Issue by Maxwell2022** [caphun/jquery.inlineedit#23]
I try to overwrite the function "encodeHtml" but it still return html value.

When saving my string it is returned interpreted. How to I overwrite the return value?

**Comment by caphun** [comment]
Hello there! Could you attach a code sample detailing what you're trying to do and the issue? How are you overwriting encodeHtml?

**Comment by Maxwell2022** [comment]
This is the test text posted to my webservice:

``` html
Test with "quotes" ampersand "&" and some 'simple quotes' with <h1>H1 tag</h1>
A new line
<h2>H2 tag on a new line/h2>

<h3>H3 tag after line break, on a new line</h3>
```

I can see it posted as such in the header of the `POST` request.

It is saved exactly like this in the database.

But I don't want to display it like this. The first time my page is loaded the content I'm escaping the value to avoid interpreting the html.

On the page load this is the value of the editable text:

``` html
Test with "quotes" ampersand "&amp;" and some 'simple quotes' with &lt;h1&gt;H1 tag&lt;/h1&gt;<br>
A new line<br>
&lt;h2&gt;H2 tag on a new line&lt;/h2&gt;<br>
<br>
&lt;h3&gt;H3 tag after line break, on a new line&lt;/h3&gt;
```

Now if I click edit, for each `<br>` there is 2 new lines and when saving it's displaying the interpreted HTML code.
I think it's the way the plugin is encoding the new value that is causing issue and I try to modify it but without real success.

**Comment by caphun** [comment]
@Maxwell2022 if you set nl2br to false it shouldn't add the extra br's. As for the interpreted HTML. Yes, the plugin returns the rendered HTML instead of the naked value.

**Comment by Maxwell2022** [comment]
wow, it was 8 months ago. I don't remember.
