### ISSUE TITLE
Activate the inline edit out side of clicking on the field.

### ISSUE THREAD

**Issue by BenBish** [caphun/jquery.inlineedit#24]
How could I accomplish this? For example clicking on an edit link elsewhere in the page would activate the inline editing for the field?

Thanks.

**Comment by caphun** [comment]
@BenBish like this:

```
$('#editable_01_trigger').bind('click', function() {
    $('#editable_01').trigger('click.inlineedit');
    return false;
});
```

Where "editable_01" is the editable region and "editable_01_trigger" is the edit link elsewhere on the page.

**Comment by BenBish** [comment]
@caphun I must have missed this. Thanks!
