### ISSUE TITLE
Hover doesn't work (fix included)

### ISSUE THREAD

**Issue by flashmob** [caphun/jquery.inlineedit#3]
- Using jquery.inlineedit.js October 01, 2010
- jquery 1.5.1
- Problem: Hover does not work

Solution: Edit jquery.inlineedit.js, find:

.live( ['click', 'mouseenter','mouseleave'].join(namespace+' '), function( event ) {

change this line to:

.live( ['click', 'mouseover','mouseout'].join(namespace+' '), function( event ) {

Started working for me :)

**Comment by caphun** [comment]
Fixed. See:

https://github.com/caphun/jquery.inlineedit/commit/116588a1352417a8b2c75815850e46b0234e5933

Thanks!
