### ISSUE TITLE
work with existing <input>

### ISSUE THREAD

**Issue by chrisbraddock** [caphun/jquery.inlineedit#4]
Hey!  First, thanks for the great work.

I'm trying to use your plugin in a Rails app with the [form helper](http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html).

So by default I'll already have an input element that'll have some attributes I want to use, e.g.

<input id="" name="course_item[name]" size="30" type="text" value="Content">

I'd like to point inlineEdit at that input and have it do its thing.  Is that currently possible or an easy mod?

**Comment by connor** [comment]
Hey Chris,

I'm using it in a rails project with no problem. 

From my understanding of Rails, it automatically gives all <input> tags an ID. If that's the only <input> you'll be using it with, you can simply just target that one:

$("#yourInputID").inlineEdit();

Does that help at all? If not, be a bit more specific and I'd love to help you out!

**Comment by chrisbraddock** [comment]
I think that probably does help.  I probably made a very silly assumption that since the example uses a span as its target, that the plugin was not designed to work with an input. :S  I'll give it another try this week.  Thanks!
