### ISSUE TITLE
Unable to click

### ISSUE THREAD

**Issue by xeor** [caphun/jquery.inlineedit#6]
Using the select widget like https://github.com/caphun/jquery.inlineedit/blob/master/demos/extensions.html behaves weird. In firefox, I am unable to select any item with a mouseclick, only with the keyboard.
Also, if I create a new control, like:
    $('<div><input type="checkbox" name="test" checked /></div>').clone().remove().html() + this.buttonHtml();
I am unable to click it at all..

I am no javascript guru, but there is a lot going on when I take a look at this with firebug and trying to select or click something.

**Comment by caphun** [comment]
I just too a look at this (sorry took me so long to get round to this!). Yep, the extension feature isn't working in Firefox! Has anyone figured out the problem?

**Comment by reinoldus** [comment]
I have figured it out and fixed it

See my pull-reqeust for fix

**Comment by caphun** [comment]
Thanks @reinoldus !
Tested and merged https://github.com/caphun/jquery.inlineedit/pull/20
